import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Slinky GHE Design & Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="introduction__content">
          <span>
            Lorem ipsum, dolor sit amet consectetur
            adipisicing elit. Magnam aliquid est quam odit,
            a numquam necessitatibus, iusto cupiditate deserunt
            quaerat voluptates quos earum magni! Rem ipsam quasi iure excepturi eveniet.
          </span>

          <button>
            Download
          </button>
        </div>
      </main>
    </>
  );
}
